baseURL = "https://cineclub-fi-udec.netlify.app/"
languageCode = "es-cl"
title = "Cineclub FI UdeC"
theme = ["hugo-creative-portfolio-theme", "darths-hugo-shortcodes-master"]
#languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "blue"
  description = "Cartelera del Cineclub FI UdeC"
  copyright = "&copy;2025 Cineclub FI UdeC"
  sidebarAbout = [
    "Cine gratis en la Facultad de Ingeniería de la Universidad de Concepción",
    "Funciones abiertas a la comunidad y con entrada liberada."
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "cineclubfiudec@gmail.com"

    # Optional Matomo analytics (formerly piwik)
      # [params.analytics.matomo]
      #  URL = "https://stats.example.com"
      #  ID = "42"
      #  # Track all subdomains with "*.example.com" (Optional)
      #  domain = "www.example.com"
      #  # Optional integrity check hash
      #  hash = ""

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Cartelera"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "Acerca"
  url = "about/"

  [[params.navlinks]]
  name = "Cineforos"
  url = "cineforos/"

  [params.social]
  #facebook      = "full page or profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  email         = "cineclubfiudec@gmail.com"
  #twitter       = "full profile url in twitter"
  #linkedin      = "full profile url in linkedin"
  #stackoverflow = "full profile url in stackoverflow"
  instagram     = "https://www.instagram.com/cineclubfiudec/"
  #github        = "full profile url in github"
  #gitlab        = "full profile url in gitlab"
  youtube       = "https://www.youtube.com/@CineclubFIUdeC"
  letterboxd    = "https://letterboxd.com/cineclubfiudec/"
  #whatsapp      = "wa.me service link"


